### ISSUE TITLE
gravity

### ISSUE THREAD

**Issue by pachamaltese** [ropensci/onboarding#248] opened 2018-08-29 16:58 UTC
### Summary

-   What does this package do? (explain in 50 words or less):
provides estimation methods for Gravity Models

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: gravity
Type: Package
Title: Estimation Methods for Gravity Models
Version: 0.8.1
Authors@R: c(
  person("Anna-Lena", "Woelwer", role = c("aut", "cre"), email = "woelwer@uni-trier.de"),
  person("Jan Pablo", "Burgard", role = c("aut"), email = "burgardj@uni-trier.de"),
  person("Joshua", "Kunst", role = c("aut"), email = "jbkunst@gmail.com"),
  person("Mauricio", "Vargas", role = c("aut"), email = "mvargas@dcc.uchile.cl")
  )
Description: A wrapper of different standard estimation methods for gravity models. 
  This package provides estimation methods for log-log models and multiplicative models.
Imports: lmtest,
  sandwich,
  glm2,
  MASS,
  stats,
  censReg,
  survival,
  multiwayvcov,
  tibble,
  magrittr,
  dplyr,
  tidyr,
  purrr,
  rlang,
  Rdpack
RdMacros: Rdpack
Depends: R(>= 3.4.0)
License: GPL-3 + file LICENSE
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.0
Suggests: knitr,
  rmarkdown
VignetteBuilder: knitr
```

-   URL for the package (the development repository, not a stylized html page):

https://github.com/pachamaltese/gravity

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

reproducibility, because it can do the same as stata gravity model estimation but without depending on propietary software, it works on different platforms (tested on Windows, Ubuntu and OS X)

-   Who is the target audience and what are scientific applications of this package?  

Students and researchers from these disciplines (but not limited to): economics, sociology, political science and geography
It can be quite difficult to get an overview of the different methods and implement them in R, gravity package provides a wrapper of different standard estimation methods. By considering the descriptions and codes of these methods, users get a comprehensive and application-oriented access, see which method may be suitable for certain research questions or data types, and extend the code available for their specific research projects.

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

The old version of gravity https://cran.r-project.org/web/packages/gravity/index.html
This is an updated version in collaboration with the original authors

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [ ] has a test suite.
- [x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  
- [x] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [x] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [x] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
    - [ ] The package is novel and will be of interest to the broad readership of the journal. 
    - [ ] The manuscript describing the package is no longer than 3000 words.
    - [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
    - (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no gaurantee that your manuscript willl be within MEE scope.*)
    - (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
    - (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by maelle** [comment] 2018-08-30 17:30
:wave: @pachamaltese! Thank you for your submission! However, it is out of scope because it is primarily a statistical method implementation tool which doesn't fall under our reproducibility category.

**Closed by maelle** 2018-08-30 17:30 UTC
Labels: out-of-scope, package
