### ISSUE TITLE
heatwaveR

### ISSUE THREAD

**Issue by robwschlegel** [ropensci/onboarding#219] opened 2018-05-25 12:27 UTC
### Summary

-   What does this package do? (explain in 50 words or less):
This package serves as an updated R version for code that was initially written in Python and then ported to R. The function of this package is to ensure reproducibility and comparability of research outputs for anyone studying (marine) heatwaves by ensuring comparability between languages and providing a speed boost.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: heatwaveR
Version: 0.2.6.9002
Date: 2018-05-25
Title: Detect heatwaves and cold-spells
Description: This package is designed to include and encompass the different methods of defining and detecting extreme events, known as heatwaves or cold-spells in both air and water temperature data. These detection algorithms may be used on non-temperature data as well however, this is not catered for explicitly here as no use of this technique in the literature currently exists.
Type: Package
Authors@R: c(person("Robert W.", "Schlegel", role = c("aut", "cre", "ctb"),
    email = "robwschlegel@gmail.com",
    comment = c(ORCID = "0000-0002-0705-1287")),
    person("Eric C. J.", "Oliver", role = "aut",
    comment = c(ORCID = "0000-0002-4006-2826")),
    person("Albertus J.", "Smit", role = c("aut", "ctb"),
    comment = c(ORCID = "0000-0002-3799-6126")))
Maintainer: Robert W. Schlegel <robwschlegel@gmail.com>
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
ByteCompile: true
RoxygenNote: 6.0.1
Depends: R (>= 3.00), data.table
Suggests:
    tidyverse,
    testthat,
    knitr,
    rmarkdown
Imports:
    tibble,
    ggplot2,
    lubridate,
    dplyr,
    tidyr,
    stats,
    utils,
    zoo,
    imputeTS,
    grid,
    lazyeval,
    RcppRoll,
    Rcpp (>= 0.12.16),
    RcppArmadillo
LinkingTo: Rcpp, RcppArmadillo
NeedsCompilation: yes
VignetteBuilder: knitr
URL: https://robwschlegel.github.io/heatwaveR/index.html
```

-   URL for the package (the development repository, not a stylized html page):
https://github.com/robwschlegel/heatwaveR

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

reproducibility, this is the primary purpose of this package, to ensure that all research carried out on heatwave analysis at least begins with the exact same algorithms and within the same framework

-   Who is the target audience and what are scientific applications of this package?  

The target audience is any researcher(s) that would need to calculate the occurrence and severity of extreme (thermal) events in air or sea. The scientific application of this package is the calculation of said events, known as heatwaves. The definitions for these events provided in this package match exactly to those proscribed in Hobday et al. (2016), and which have become the standard for marine heatwave detection in Canada, Australia, and South Africa.

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

There is an older version of this package that may be found here:
https://github.com/ajsmit/RmarineHeatWaves
The reason for this update was to bring the older R version more in-line with the original Python version found here:
https://github.com/ecjoliver/marineHeatWaves/
This new R version also provides a serious speed boost with the inclusion of Rcpp functions. It has also been redesigned from the ground up to meet best package practices as laid out by rOpenSci.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

### Requirements

Confirm each of the following by checking the box.  This package:

- [X] does not violate the Terms of Service of any service it interacts with. 
- [ ] has a CRAN and OSI accepted license.
- [X] contains a README with instructions for installing the development version. 
- [X] includes documentation with examples for all functions.
- [X] contains a vignette with examples of its essential functions and uses.
- [X] has a test suite.
- [X] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coveralls and/or CodeCov.
- [X] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [X] Do you intend for this package to go on CRAN?  
- [X] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [X] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
    - [ ] The package is novel and will be of interest to the broad readership of the journal. 
    - [ ] The manuscript describing the package is no longer than 3000 words.
    - [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
    - (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no gaurantee that your manuscript willl be within MEE scope.*)
    - (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
    - (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [X] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [X] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by noamross** [comment] 2018-05-26 20:52
Thanks for your submission, @robwschlegel et al!  This looks like a very useful package and an improvement over existing options. However, I'm afraid it falls out of scope for us, because it is primarily a statistical method implementation and visualization tool,  neither of which fall under our [reproducibility or other categories](https://github.com/ropensci/onboarding/blob/master/policies.md#package-categories).

Nevertheless, we have many ocean folks in the rOpenSci community who would likely be interested in this package - I'll direct them to your repo to try this out.  And I'd encourage you to submit to [JOSS](http://joss.theoj.org/).

**Comment by robwschlegel** [comment] 2018-05-28 05:57
Hello Noam,
Thank you for the rapid response. I understand that our package is not
quite the right fit but thought I would submit it anyway.
I'll definitely still be putting it on CRAN and submitting to JOSS.
All the best,
-Robert

**Closed** 2018-05-28 16:57 UTC
Labels: out-of-scope
