### ISSUE TITLE
humanleague

### ISSUE THREAD

**Issue by virgesmith** [ropensci/onboarding#166] opened 2017-12-04 21:46 UTC
### Summary

-   What does this package do? (explain in 50 words or less):
humanleague is a python and an R package for microsynthesising populations from marginal and (optionally) seed data, using a selection of algorithms: IPF, direct quasirandom sampling, and quasirandom sampling of IPF. 

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: humanleague
Type: Package
Title: humanleague: a Synthetic Population Generator
Description: Generates high-entropy integer synthetic populations using quasirandom sampling, in arbitrary dimensionality. Also implements IPF for reference.
Version: 2.0.1
Author: Andrew Smith
Maintainer: Andrew Smith <a.p.smith@leeds.ac.uk>
License: MIT + file LICENCE
Encoding: UTF-8
LazyData: true
Imports:
    Rcpp (>= 0.12.8),
    curl
LinkingTo: Rcpp
RoxygenNote: 6.0.1
Suggests: knitr,
    rmarkdown,
    testthat
VignetteBuilder: knitr

```

-   URL for the package (the development repository, not a stylized html page):
https://github.com/virgesmith/humanleague

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

data munging and reproducibility. The package generates synthetic populations typically from marginal data from e.g. census, and produces deterministic results given either by a controllable quasirandom sequence, or simply seeking the highest-entropy solution using a well-known algorithm. 

-   Who is the target audience and what are scientific applications of this package?
Georgraphers, demographers, agent-based modellers, and others who microsimulate populations for e.g. policy guidance

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

mipfp is perhaps the best-known package that implements IPF in R. My package overlaps in that it implements the same algorithm using in a faster C++ implementation, but it also goes much further and introduces two new algorithms for sampling integer populations, which may be of interest specifically for individual-based simulations including ABM 

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

### Requirements

Confirm each of the following by checking the box.  This package:

- [X] does not violate the Terms of Service of any service it interacts with. 
- [X] has a CRAN and OSI accepted license.
- [X] contains a README with instructions for installing the development version. 
- [X] includes documentation with examples for all functions.
- [ ] contains a vignette with examples of its essential functions and uses.
- [X] has a test suite.
- [X] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coeveralls and/or CodeCov.
- [X] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [X] Do you intend for this package to go on CRAN?  
- [X] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [X] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [X] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [x] The package is deposited in a long-term repository with the DOI: [![DOI](https://zenodo.org/badge/95961787.svg)](https://zenodo.org/badge/latestdoi/95961787)
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
	- [ ] The package is novel and will be of interest to the broad readership of the journal.
	- [ ] The manuscript describing the package is no longer than 3000 words.
	- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal.
	- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [X] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [X] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by karthik** [comment] 2017-12-12 18:46
Dear @virgesmith 
Thank you very much for the submission of `humanleague` to rOpenSci's review system. After discussion with the other editors, we have decided that your submission is out of scope for us since it falls under statistical algorithms/methods which is a category that we are simply unable to review at this time. Although this package does involve a lot of data munging and helps with reproducibility, it is not general enough for the rOpenSci suite at this time. We appreciate your efforts and encourage you to seek review elsewhere. If our system expands to other areas, we welcome a resubmission.

**Closed by karthik** 2017-12-12 18:46 UTC
